### ISSUE TITLE
Save person when Availability Change Edit button is clicked

### ISSUE THREAD

**Issue by cjfullerton** [UoMResearchIT/CapX#120]
At the moment doing this wipes the unsaved person.

**Comment by aharwood2** [comment]
Thanks Chris. I know what the problem is and should be easy to fix. Basically the entity is not given a primary key until the context is saved to the DB. This only happens when you click the save button at the moment. I can easily make it save when clicking the edit button too so that the next page can use the primary key to determine to which entity the availability changes will belong!

**Comment by aharwood2** [comment]
Fixed in the next release.
