### ISSUE TITLE
Burn-Up Chart not showing gap

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#200]
In RTP-86, there is a gap between 31-Sep-2024 and 07-Oct-2024 (this is correct).  However, the burn-down chart doesn't show this gap.  I would have expected a horizontal section representing the 1 week of gap.

![burnup-chart](https://github.com/UoMResearchIT/CapX/assets/213274/b42fa396-0f45-46ac-b46b-252e5ae0f854)

**Comment by aharwood2** [comment]
This is interesting. Both 30th Sept and 7th Oct are Mondays and hence the beginning of a week. The resolution of the graph is based on the week beginning so the reason you don't see the flat line is because the graph samples the data down from daily resolution to weekly resolution and loses the granularity of how many days a task actually takes within the week.

The way the sampling is done is to average out the planned work for the task over the number of whole weeks it runs in rounded up. So essentially "Dev 1.5" starts on Thursday 1st August (w/c/ 26th August) runs until 30th September inclusive (w/c/ 30th September) this is considered to be 6 weeks for the purposes of the sampling when in reality is 5.57 weeks. The planned work is 103.6 hours which is then averaged to be 17.26 hours spread evenly over the 6 weeks and that is what is shown on the graph. If you want it to be a more accurate picture then we can change the sampling logic to maintain the granularity?

**Comment by aharwood2** [comment]
I've adjusted the logic so it is more granular so this should be fixed in the next version:


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/b1ce37a7-ad1e-4979-a412-c6b01a96a971)
