### ISSUE TITLE
Understanding Project & Task types and costs

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#24]
Most portfolio projects are for a percentage FTE. It would be nice to simply be able to input the FTE and duration (e.g. 50% for 2 years) and have it automatically calculate the budget (e.g. that example would be approx. £58000).

**Comment by aharwood2** [comment]
Yes, I guess the premise the task system is built on is forward-scheduling so the end date is always drive by either a fixed duration or a a fixed amount of work. To get what you want you would have to put a task in for a fixed duration of 730 days. However, there is still a problem -- I haven't set the system up with holidays or annual leave or anything like that. So assigning someone at 50% for the 0.5 FTE would set the number of hours work too high as it would just calculate the number of business days in that period rather than taking into account holidays/leave/closure days.

I suppose we are getting into capacity planner territory here but if we make an RSE only avaialble for 0.8FTE then assign them at 40% when someone asks for an RSE at 0.5FTE then it should be roughly correct? I'll start some documentation.

**Comment by aharwood2** [comment]
Doing the numbers more closely means that we are actually avaialble to work on projects 0.84 FTE (220 days out of 261 business days) so we could assign someone 42% to a project when they have been asked for 0.5 FTE and the hours will then work out right. Not pretty but I guess that's why the capcaity planner uses that weird 4 day thing.

**Comment by aharwood2** [comment]
I guess the feature request here is just an easy way to set this up but I think it is probably straightforward enough to say use a fixed duration task of 730 days for a 2 year project and then assign someone at 42% to get the 0.5FTE you are looking for? I've started to add some documentation in the README.

**Comment by ajerrison-manchester** [comment]
At present we can only add an RSE at granularity of 0.1, i.e. 0.8 or 0.9. So we'll need an enhancement to allow 0.84!

**Comment by ajerrison-manchester** [comment]
I guess my point also is about how we calculate costs - it isn't necessarily a day rate but a PCM. I am guessing that the research support office calculates the salary/oncosts at grade 7.1 for the first year, 7.2 for the second year, and so on. However we don't see that total so don't know what it is! I'll just put it on at 220 x 295 at present, but that isn't strictly what we are actually getting.

**Comment by aharwood2** [comment]
> At present we can only add an RSE at granularity of 0.1, i.e. 0.8 or 0.9. So we'll need an enhancement to allow 0.84!

Yes, this is going to be in Friday's release.

**Comment by aharwood2** [comment]
> I guess my point also is about how we calculate costs - it isn't necessarily a day rate but a PCM. I am guessing that the research support office calculates the salary/oncosts at grade 7.1 for the first year, 7.2 for the second year, and so on. However we don't see that total so don't know what it is! I'll just put it on at 220 x 295 at present, but that isn't strictly what we are actually getting.

This is also a tricky one and I've tried to add something to the documentation but it is an issue. The total costs of everything are calculated using the day rate at the moment. For "Fixed Work" tasks, this is fine as we keep track of these based on the number of hours so holidays/closure days don't matter. The scheduling system works out this fine. If someone goes on hoilday, we can split a task to allow for a pause to recalculate the end date if necessary. Costs add up nicely to the budget.

The problem comes with the PCM payments. The money we recover will not add up to the number calculcated by the tool since the "day rate" will be different based on the person's spine point. Also, the project essentially pays for holiday and closure days unlike the journal version. I am hoping to change the process so that we only pay people one way but that is going to take time. I've been using "Fixed Duration" tasks for these types of arrangements and it does cost the holidays and closure days so typically CapX will work out a cost higher than the budget if we quoted the customers on 220 / year. Not worked out how to solve this yet but the we can specify a budget for a project manually so even if the sum of the costs of the tasks doesn't add up we still have a record of what we agreed.

**Comment by aharwood2** [comment]
I've updated the README with some more information on this. The situation is less than ideal. If we did away with the PCM concept, life would be so much simpler. I'm going to close this issue but feel free to re-open if the documentation is not clear enough.
