### ISSUE TITLE
Add Project: status

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#26]
There is a funding status, but that seems to include an overall current proejct status too.

Some longer term projects might be paused for a few months or are 'active' but we are actually not doing anything at that point (e.g. we might have agreed 3 months at the beginning and end of data collection) so don't need anyone assigned right now. Some additional statuses would perhaps be useful as an overview:

Paused by PI
Active, awaiting next task

**Comment by aharwood2** [comment]
Sure, seems reasonable. Easy one :)

**Comment by aharwood2** [comment]
In light of us having a status in both the RTP Jira board as well as CapX I'm wondering whether CapX can afford to be a bit less detailed and the detailed status of the project can be in Jira instead? Otherwise we would have to maintain two lists? Will close for now but feel free to reopen if we feel we need the detail at both levels. I'm actually going to simplify the status options in CapX for this reason I think.
