### ISSUE TITLE
Projects with a missing (£0) budget could be flagged as needing attention

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#274]
Currently, there is no warning if a project has £0 for a budget.  This could be flagged as needing attention.  Unless it is normal for projects to not have the budget field filled in?

**Comment by aharwood2** [comment]
Sure -- new status messages are easy to add. In theory, every project on the board should have a budget. If it is a "free" project then it isn't really a project and it just becomes baseline which is captured via availability changes so I think this is fine.

**Comment by ianhinder** [comment]
Hmm.  I hadn't thought about free projects. Maybe we don't want to prevent people from using CapX to track information about free projects.  To support them, we could distinguish between a budget of 0 and a budget being unset (maybe with a toggle such as "No budget").  But maybe it's not worth the development time.

**Comment by aharwood2** [comment]
I think here perhaps a compromise could just be an info message rather than a warning or error reminding people that the project has no agreed budget. There might be a genuine reason for it where it isn't baseline work and budget negotiations are on-going where we might get paid for it eventually. There is one I can think of like this.
