### ISSUE TITLE
Delete a task

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#28]
I don't seem to be able to delete a task, unless I've missed something! I guess we shouldn't be able to delete one if it is currently being worked on though, so it might need a status.

**Comment by aharwood2** [comment]
Ah yes, I haven't implemented this deliberately at the moment because I need to think about what order things need removing from the DB in order to mess anything up. Will get round to adding this. Trying to think if there are any issues around this but I don't think so.

**Comment by aharwood2** [comment]
Probably will implement this the same times as #47 although I at least need to do it at the same time if not before.

**Comment by aharwood2** [comment]
There is a "done" flag for a subtask that allows it to essentially be "locked" so perhpas we can enable the delete button once it is marked as done? Otherwise, I can just add a prompt to make sure it doesn't happen accidentally. I think I will need to manually delete resources that are assigned to the task as part of the delete process so will do all that in the service layer. The project itself will then need to be updated in the DB to ensure it no-longer references the sub task and of course its summary data will need updating but that may happen automatically on a page refresh but will take a look.

**Comment by aharwood2** [comment]
Done!
