### ISSUE TITLE
Tasks: simple editing of dates, days and hours

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#29]
For a project that is a percentage FTE then it would be nice to enter a task as (e.g.) start date, 01/02/23, end date 01/08/23, percentage 40%. And then the screen work out the rest! I found that I couldn't really enter all I needed to with any of the options currently there.

**Comment by aharwood2** [comment]
This is by design really based on the forward-scheduling paradigm. We could potentially allow users to pick an end date and it work out the duration of the task but it would essentially be only available if the task is "fixed duration". Anything else and the end date should most certainly be driven by the work or units (assigned percentage). It should be straigthforward to add this option to the fixed duration task for the next release.

**Comment by aharwood2** [comment]
OK, not quite as straightforward as I'd hoped as I had to take into account what would happen to a fixed duration task if the predecessor was reschuled but I got there in the end!
