### ISSUE TITLE
Implement a way to silence warning about historical unmet demand

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#303]
At the moment, any unmet demand on a project is flagged as an item needing attention.  But in some cases, this is historical, and there's nothing we can do to meet that past demand. Can we silence the warning for historical unmet demand? Is that the right thing to do, or would we sometimes want to "meet" that demand in future and delete the earlier unmet task?

e.g. RTP-123

<img width="1227" alt="image" src="https://github.com/UoMResearchIT/CapX/assets/213274/6dce3492-8556-4d24-a4df-b8e9ee9f0458">

**Comment by aharwood2** [comment]
I've adjusted the warning at the project level so that it won't show if the un met demand is in the past. I have left the warnings on the task itself so you will still see it in the task grid as per your screen shot but it won't propagate up to the messages under the project heading or on the project card on the home screen. Is that OK? I didn't want to necessarily lose the indication completely if it is in the past.

![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/8cf64ece-ff60-436d-b72e-816a5437a0e0)


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/91e9ea2a-fa52-4503-beab-3497cb76c860)


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/f8c57806-cd58-4231-aa4e-0ad69a2c5339)


![Image](https://github.com/UoMResearchIT/CapX/assets/8614261/9dc06f62-f732-40e7-92c9-8b8a94a8f91d)
