### ISSUE TITLE
Too easy to lock myself out a project

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#355]
When creating a new project (RTP-260), I didn't assign a project manager, since while I am handling the demand process, I figured I wasn't necessarily going to manage the project. Big mistake! Since only project managers are able to edit the project, I now cannot update the details, nor assign myself as the project manager!

I don't think it makes sense to be able to create something that you then can't edit. So maybe the project manager field should default to the user creating it, and if it is changed, a big warning should be displayed that you will lose write access to the project if you are not the manager. This will make it clear that the person handling the demand process should be listed as project manager, even if this is then going to be handed over when the project starts, which I assume is the intent? (does this actually happen?)

**Comment by aharwood2** [comment]
OK so I guess there are two things here:
- [x] Present a warning when changing the PM and not a superuser to warn of loss of access
- [x] Set the PM to the active user by default

In the mean time, I'll restore your access to 260 :)

**Comment by aharwood2** [comment]
OK, I've set the PM to the active user by default. I've also made it so that not setting a PM causes a validation fail on the form so you can't save any changes. I've also added a message to say that if you change the drop down selection to someone who isn't you and you aren't a superuser that you get a message box stating you are about to lose edit access to the project.
