### ISSUE TITLE
Something is broken, but not obvious what!

### ISSUE THREAD

**Issue by rowleya** [UoMResearchIT/CapX#359]
When I go to RTP-197, I get an unknown error.  I can no longer interact with that project at all, as the error makes me refresh the page, which doesn't work...

**Comment by aharwood2** [comment]
Interesting. I will check the logs. I notice that if I go to the page with the [filteredNote query parameter set](https://balex.itservices.manchester.ac.uk/projectdetails?rtp=197&filteredNote=200) it loads the page fine. Also seems OK when the "Show Only Note Due" switch is enabled but again no notes are actually show. I wonder if there is some data corruption in the notes DB table thanks the the last bug I fixed #343 and #339 that is now causing an issue when trying to render the note content for one or more notes? Will post back here when I've checked the logs.

**Comment by rowleya** [comment]
Yes, could be.  It definitely seems related to notes - I just added one so hopefully that has made it in, but it is possible that because I had something due it did something else.

**Comment by aharwood2** [comment]
OK -- The logs tell me little other than there is a null property somewhere that it doesn't expect to be null. Digging into the DB, it looks as though one note in particular has a completed date set but no due date. The due date is null. When I add a due date into the record the crash doesn't happen and the notes load OK. I can either patch the code to let a note have a completion date but no due date or I can fix the messed up records. Theoretically, you should never be able to set the completion date without first setting the due date as it has to have a due date before the done button is shown. The bugs I referred to above would definitely screw this up as the issue was that they were setting the completion date on the wrong records when the button was pressed -- clearly records that didn't even have a due date in this case. This will require a direct DB intervention to fix. Look at the DB -- this is the only broken record. I'll probably fix it tonight at silly o'clock when I know no-one sane is using the system :)

**Comment by rowleya** [comment]
OK, thanks!

**Comment by aharwood2** [comment]
OK fixed the DB now so hopefully this is resolved.

**Comment by rowleya** [comment]
Yes, fixed for me now - thanks!
