### ISSUE TITLE
Error if actuals have not been touched

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#371]
Some project entries in CapX are supposed to be updated periodically, such as task Actuals from Innate. For an active project, we could add a warning to the project when the Actuals have not been updated in the last month (as per the PSM Guide). Other fields could also have warnings added when they have not been touched.

**Comment by aharwood2** [comment]
I can make this issue about the actuals and then worry about other fields as and when?

**Comment by rowleya** [comment]
I would personally say the actuals would be useful as it would remind me to do it!

**Comment by aharwood2** [comment]
An error would certainly force action. Difficulty is going to be how to police it. I guess for active projects the actuals should increase until the project is in any other state than active? Other than people not working on it when they should, or timesheets not getting approved I can't see any reason why this error would be inappropriate. Perhaps if someone went on holiday for a month? But then I guess the status can be changed to paused.

Also, if it does go to paused and then back to active, do we reset the clock? Otherwise an error would appear instantly?

Essentially I can record when the value of the actuals was last changed for a task but I feel there is going to be nuance here as to when is an appropriate time to display the error. I'm going to bump this to the next version as it is more complicated than it sounds I think.

**Comment by ianhinder** [comment]
One option would be to implement it with a long grace period, e.g. 4 weeks, to catch those cases where the actuals are really out of date, but which should not affect most people negatively. Then the next iteration of the feature could have a tighter grace period, but with some more thought put into it. Or just leave it, as you said.

**Comment by rowleya** [comment]
I don't think this is critical, more of a nice-to-have.  Some thoughts:

1. We do know when people are on leave now in CapX (assuming they update it).  I don't think this is necessary to consider given the below however.
2. This can just be a "how long since last updated" thing i.e. just a marker when someone actually pressed the save button on it.  They can even leave the value as it is so long as they save it again.
3. The "red text" that then appears if it has been left too long is an error, but it doesn't break anything.  
4. If then someone pauses a project and then resumes it, this could indeed reset the counter, but it could also not, and then they have to go and set it in case some of them have changed since they changed the status (which might happen later than it should)

Hopefully that makes it easier to implement.

**Comment by aharwood2** [comment]
Thanks both. Regarding 2, I was thinking that if someone updates the description and hits save then it would reset the clock and they never even looked at the actuals. Really limits how useful this is if that is the case. I think we need something but I there may need to be some model redesign to make it a proper control.

**Comment by rowleya** [comment]
That is true, but I think it depends what you (or others) want from it.  For me I would just want it to be a useful reminder.  I personally am not going to just skip doing it to get rid of a warning or error, and I would like to think that would be true of most people in that position, but I guess who knows!

**Comment by aharwood2** [comment]
Now finance stuff is starting to be introduced into CapX, I think this is going to be more important so bumping it up in priority.

**Comment by aharwood2** [comment]
Gone for the simplest solution for now which is if your project is active and the value in the actuals box hasn't changed for a month then you get an error. To silence this you need to either change the value of the project actuals or you can click a button on the summary table which will do it manually. It has a prompt.
![Image](https://github.com/user-attachments/assets/4faeadce-ad99-4289-a79c-07495c17771a)
