### ISSUE TITLE
"Filter Manager" option in Capacity should show all people if all or none are selected

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/CapX#436]
No matter who is selected it returns "No data to show for the selected people."

Possibly we don't actually have line managers saved in the dataset, so this filter can't work until that data is added.

**Comment by aharwood2** [comment]
So this has come up before I thi K. It does work but perhaps it doesn't work as you expect it to (which in itself is an issue). When selecting a PM you also have to select the people (it defaults to none selected so shows nothing initially). If you select all people after selecting a manager you will see what you expect. I'll change the title of the issue I think.

**Comment by rowleya** [comment]
I think I thought this was Line Manager, but of course it is Project Manager!  When I tried this with "all people" selected, this creates lots of empty charts, which is a bit odd!  Possible ideas then:
 - When a PM is selected and no people are selected, reduce the initial chart displayed but keep it combined
 - When a PM is selected and multiple / all people are selected, only show charts for those where there is data.  It may be useful to list the ones with no data at the bottom just to indicate that the request has been received correctly.

**Comment by aharwood2** [comment]
Following @rowleya 's suggestion here I have made some progress as those changes in themselves were quite easy to make. What isn't easy to make is that the colour scheme used is then non-standard i.e. it is different depending on whether a manager is selected or not. It is doable but will take more time. Current issues for me to work through:

- [x] Refresh page and it doesn't reload the graph properly -- after the value is loaded from session storage, the chart is drawn before the people filtering happens, will need to see how this is initialised.
- [x] Clicking data point does nothing when manager selected -- possibly the logic is being restricted by the chart more so can relax this.
- [ ] Colouring on the view where manager selected but no people selected is not helpful has it only considers projects that manager owns to calculate someone's relative load and hence the colouring rather than all their projects.
- [ ] Colour on the manager selected and person selected is similarly not useful as the total bar is coloured with respect to the projects the PM owns not their whole load -- as above, it is because the colouring is based on the data source for the chart which is now filtered based on the manager; might need a more significant rework.
- [x] Still getting people included where they are on a project that is not in the correct state -- might be including finished projects etc so will need to see w that project list the people filter method is using

**Comment by rowleya** [comment]
A possible option to simplify at this point would be to just display the charts separately as it is now, but reduced to only show people where there is data, and to show as if all people are selected when none are i.e. to basically remove the idea of the combined but reduced chart.  That would then avoid the need to recalculate everything...

**Comment by aharwood2** [comment]
I'm going to skip the items regarding the colouring for this issue as we can resolve that on a separate issue if necessary. I'm not really sure what would be useful here anywhere. Ultimately, the bug this issue relates to is fixed now so can close.
