### ISSUE TITLE
Mentions with "@" lead to extra characters

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#453]
When I try to mention someone, I type "@" followed by the first letter of their name. A menu appears allowing me to select people. When I click on a person, it appends their initials to the text, but doesn't remove the characters I have already added, so the mention is invalid.

https://github.com/user-attachments/assets/ee9ef4d0-80a7-4ac2-8a73-7dbd183f324d

**Comment by fdq09eca** [comment]
~~[line 30](https://github.com/UoMResearchIT/CapX/blob/bb88eca881f2f02f786d31db1e16b6d0f030b0a8/PPMTool/Pages/ProjectDetails.razor.js#L30) should be the problem, should not add the name right behind the cursor, but behind `@` and replace the text until next word.~~

After some investigation, it is more likely the async problem happen at the following:

https://github.com/UoMResearchIT/CapX/blob/bb88eca881f2f02f786d31db1e16b6d0f030b0a8/PPMTool/Pages/ProjectDetails.razor.cs#L434-L442

After `@` is typed, the expected behaviour should be the following:

1. popup the contact list 
2. set cursor focus on the search text box
3. user input search text in the search text box (Optional)
4. filter the context list
5. user select the desired contact
6. insert the desired contact's initial to the text box


however, because line 439 is async, user can continue input after `@` in the text area until 1 and 2 is completed. 

we may 
1. turn the async in to sync.
2. suggest user wait a little bit..?

**Comment by aharwood2** [comment]
This was designed so that you type @ and then wait for the menu. If you keep typing then it just dumps the characters to the editor while the menu is not present. If you really don't want to wait for the menu then we can modify the insert code to do a backward search and remove characters up to the @ symbol before it inserts the initials.

**Comment by ianhinder** [comment]
I guess my usage is a hybrid between using the menu exclusively (i.e. scrolling down to find the person after typing "@"), and ignoring the menu and just typing the initials. I usually type the first initial or so, then click on the menu to get it completed, like I would with the tab key in a terminal. If you could do the search and remove, that would be great, thanks! It also makes it the same as the way GitHub and Teams work, as a bonus. (bonus if Tab does the completion as well, to avoid needing to use the touchpad!)
