### ISSUE TITLE
Delete a project

### ISSUE THREAD

**Issue by TheresaTeng** [UoMResearchIT/CapX#47]
Is it a feature that a project cannot be deleted?

Tasks:
- [x] Complete #28
- [x] Complete #49 
- [x] Implement the methods/services to remove the project from the DB entirely and clean up

**Comment by aharwood2** [comment]
Just an omission as deleting a project is not so easy to do as there will be a bit of clean-up needed. Also relates to #28 .

**Comment by aharwood2** [comment]
In light of how we are handling projects that have not been funded etc, I'm wondering whether we should add this option or not actually. I'll have a think about it for v1.3 I think.

**Comment by aharwood2** [comment]
I'd like to add a prompt to this option so that people are prompted to only delete a task if it was created by mistake. Projects that are not funded or requests that are cancelled need to remain but with their status set appropriately as we are going to track the percentage of projects not funded or cancelled in future.

**Comment by aharwood2** [comment]
Done, will be available in v1.3
