### ISSUE TITLE
Marking a resource allocation as "provisional"

### ISSUE THREAD

**Issue by PhilBradbury** [UoMResearchIT/CapX#50]
It would be useful to be able to allocate someone to a project/area on a provisional basis, so it's clear that their time is already being looked at.

**Comment by aharwood2** [comment]
Yes, this is useful. The capacity sheet would then use a different shading for these. Maybe a hatched rather than a solid colour. Will have to see what the charting API allows.

**Comment by aharwood2** [comment]
This can be done in two senses actually -- a provisional allocation can be shown as hatched based on a flag on the resource allocation table, but also we can show it hatched if the project is not funded as this is also a kind of provisional assignment.

**Comment by aharwood2** [comment]
Yep, looks the the JS library permits this so I'm guess the Blazor API will expose it too...I hope: https://apexcharts.com/docs/options/fill/#pattern

**Comment by aharwood2** [comment]
Tasks I think need doing to achieve this:
- [x] Add flag to Resource model to indicate whether an assignment is provisional
- [x] Modify the resource grid to load / store provisional state
- [x] Modify capacity displays to hatch a block if it contains a provisional assignment on one of the subtasks
- [x] Modify the project details Gantt to colour based on unallocated and hatch if provisional

**Comment by aharwood2** [comment]
This is not going quite as I'd like. The API only lets you colour entire series on the plot with a fill pattern. Because the bars in the chart are considered "DataPoints" in a series, which represents everything you see on the chart, we are asking it to permit us to fill individual data points with a pattern. I guess this is not normal behaviour for charts in general so it actually can't be done. As a best compromise for now I have added a background shade to the tooltip on hover when a bar contains a provisional assignment. Best I can do for now 😞
