### ISSUE TITLE
Email notifications appear to be broken

### ISSUE THREAD

**Issue by ianhinder** [UoMResearchIT/CapX#542]
We are not getting email notifications from CapX since mid-October.

**Comment by aharwood2** [comment]
Last note I received with 16th Oct 12:05. There were patches to CapX on 15th, 16th and 17th October. Looking at the diff though, there were no changes anywhere near the Email Service. It is possible that something has changed with the server. I will pull the logs and see if there are any email failures. Otherwise, I'll have to test the code manually to make sure they are being fired and at the very least ensure there is a log entry to show they are being sent to the SMTP server and we can then narrow it down.

**Comment by aharwood2** [comment]
I can't see any being sent in the logs and there are no errors either. However, I did change the log level as part of one of the patches so it is possible that this has just been suppressed by mistake. Since absence notifications appear to still be happening it is more likely some kind of failure in the code so will need to walk through it.

**Comment by aharwood2** [comment]
OK, I think I've found the cause. The failure is happening on a background thread which doesn't crash the app (of course) but also doesn't automatically log its exceptions. It was caused by Dave Benko being added to the DB; he doesn't have a "person" entry because he is not a team member and when preparing the notification emails this causes a null reference exception and the thread terminates before it sends anything. The try-catch is only wrapped around the email call at the moment, not the preparation so it was not caught and logged.
