### ISSUE TITLE
Simplify capacity colours

### ISSUE THREAD

**Issue by aharwood2** [UoMResearchIT/CapX#59]
The two tones of yellow don't really help so I think we should change this to just have a 3-state system: under, full, over.

**Comment by mawds** [comment]
I think the issue is partly the colours used.  Something like this would be good, with green = under, red = over:

![image](https://user-images.githubusercontent.com/12030124/198623717-ec92340b-b2fb-4ba0-afd4-66bca61d498d.png)

(Generated with) https://www.learnui.design/tools/data-color-picker.html#divergent

I think you need a little more granularity than simply under or over - maybe 2 or 3 each side of 100%

**Comment by aharwood2** [comment]
Introduced this colour map but with a slightly darker central colour to distinguish it from the white background.
