### ISSUE TITLE
Percentage allocation incorrect when person is not full time

### ISSUE THREAD

**Issue by ajerrison-manchester** [UoMResearchIT/CapX#62]
Only  a minor irritation, but the percentage unallocated differs when a person is not full time, i.e. it doesn't show '% FTE', but '% of % FTE', if that makes sense. :-) 

For instance for someone like myself, who is only on the system for "42%" (i.e. half), then the allocations don't quite match up to the expectations. For instance I am allocated 40% FTE to eLab. However the system shows me as allocated 80% of my capacity, but it really should be 90% of my capacity. Or just show it as 40% FTE really, to avoid confusion. Well I got confused anyway, I thought I'd calculated all my projects incorrectly for a bit. :-)

**Comment by aharwood2** [comment]
If you are assigned 40% of .84 then it should be an assignment of 33.6% which is 33.6 / .42 = 80% of your capacity. Where did you get 90% from? The fact that it is confusing though probably means this needs a rethink.

**Comment by ajerrison-manchester** [comment]
Sorry, I mean it is just appears a bit inconsistent. A full time person is 80% of capacity if they are assigned 80% FTE to stuff, however a half-time person is shown as 80% of capacity if they are 40% FTE assigned. Which is I know is technically correct, but I think I'd prefer to see the FTE assigned rather than the percentage of current availabilty. 

Because for instance depending on how you look at it I am officially either 90% FTE assigned overall, or 40% FTE assigned to projects at the moment. But if I was just taking a glance a the planner it might look as though I was available for 20% FTE which confuses me at least.

**Comment by aharwood2** [comment]
So just to be clear, do you prefer the availability to show actual FTE assigned i.e. up to 84% for a full time person and up to 42% for a half-time person and then have the colouring indicate how much of their time is actually available?

e.g. if you are assigned 2 "days per week" to projects and you are available to work on project up to half-time since you do baseline management the rest, you are technically available .42FTE (42%) and you have been assigned .336FTE (33.6%) to projects so the tooltip should show you as being allocated 33.6% and the colouring indicate that you have a further .084FTE (8.4%) left to assign?

Or would you prefer it to be "converted into the round numbers approach" to show you are assigned 40% and have 10% free?

**Comment by aharwood2** [comment]
I've changed this now to removed the normalisation with respect to availability on the values. I have, however, left the colour normalised. So when I do #64 , the tooltip will show the actual FTE assigned (e.g. 50%) but then the colouring would indicate availability so for a .5FTE person they would still be coloured to show they are fully allocated.
