### ISSUE TITLE
Confusing "delete task row" message 

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/CapX#670]
On trying to submit a timesheet, I got this message:

![image](https://github.com/user-attachments/assets/b7abf12b-c7e5-4320-ae4b-d6ede1ea2fee)

There's only one category with values in this timesheet, and two automatically added (from the previous timesheet, but not in a way that makes sense - see https://github.com/UoMResearchIT/CapX/issues/616#issuecomment-2554856581).

Which task row will be deleted? ... Let's click OK to find out! Nothing. Fine, click on cancel. ...Also nothing. Click on the "X" to exit the dialog. ... Also nothing.

**Comment by PhilBradbury** [comment]
You're having some fun with this system - sorry about that! :rofl:

The message should appear when you are choosing to remove a row by clicking the delete button. If you cancel the actuion then it should remain there, but if you continue (clicking ok) then it should remove that row from the grid on screen and also from your template so it won't automatically be in the next one you create.

**Comment by AnnieZQH** [comment]
I also encountered this issue. After trying to click on the two buttons, an error occurred and I was prompted to reload. 
What happened after the reload:
- The entries in the timesheet I was submitting was deleted and the empty timesheet was submitted
- ~~All the time entries in a timesheet with status `NEW/UNSUBMITTED` were set to 0~~
Edit: I might have mixed up two timesheets so the last point is likely incorrect, sorry!

**Comment by PhilBradbury** [comment]
@gcapes & @AnnieZQH : Okay, can you (both, preferably, just so we're sure it's the same issue) detail the actual steps you take to reproduce this, please? I can't figure out how to get it to do what it's doing for you to be able to track the bug down. 

Also, if you could provide details of what OS and browsers you are using too, please? (and perhaps check on a different browser so I have as much info to go on as possible). :)

**Comment by AnnieZQH** [comment]
The dialog issue occurred for two of my timesheets, and one of them caused an error which cleared the timesheet like https://github.com/UoMResearchIT/CapX/issues/662. I tried submitting again after the reload (ctrl+f5 hard reload) and it didn't happen again so this issue is likely just a browser cache issue, and submitting empty timesheet is a different issue.

OS: Windows 11 
Browser: Chrome Version 131.0.6778.140 (Official Build) (64-bit)

Steps:
1. Navigate to My Timesheets
2. Click "+ ADD"
3. Click "+ ADD" to add a new entry
4. Select "00 - All IT - Closure Days" and fill in the time
5. Click "SUBMIT TIMESHEET"
6. The delete task row dialog pops up
7. Click "OK" 
8. No response, the dialog is still there
9. Click "CANCEL" 
10. Same as step 8
11. Click "OK" again
12. An error occurred - there is an alert above the bottom navbar (where the version is displayed) prompting to reload, the dialog is still there though
13. Reload
14. The timesheet is empty and the status changed to submitted

**Comment by aharwood2** [comment]
This happens when you have at least one "zeroed" template row that you then subsequently don't fill in. An erroneous call to the wrong delete method is where the popup comes from. Needs patching!
