### ISSUE TITLE
Capacity planner shows availability for people who are leaving

### ISSUE THREAD

**Issue by mawds** [UoMResearchIT/CapX#96]
The capacity query shows availibity for people who are leaving. 

To reproduce:
Capacity screen, "who is available", enter 1 Sept 2023 as start, Run.  Shows me as available, even though I have a leave date (30/6/2023) entered in the system.

**Comment by ajerrison-manchester** [comment]
Related to #82

**Comment by aharwood2** [comment]
I guess this is because the graph's data range technically is the entire range of dates in the database. We could "hide" people who have an end date entered into the system but then we would have to wait to add the date until someone has actually gone. We could also put in a sort of fake task to show them as "allocated" beyond their leaving date and then if the leaving date is in the past, then hide them? Maybe I'll try that and see what it looks like.

**Comment by aharwood2** [comment]
I went with a swtich to turn leavers on or off as we might need the historical context at some point. Will be in the next release.
